### ISSUE TITLE
Add Solution for "Majority Element"

### ISSUE THREAD

**Issue by MayurJirapure11** [Kushal997-das/Hacktoberfest-2021#171]
Given an array nums of size n, return the majority element.

The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

Example 1:

Input: nums = [3,2,3]
Output: 3
Example 2:

Input: nums = [2,2,1,1,1,2,2]
Output: 2
 

Constraints:

1.  n == nums.length
2. 1 <= n <= 5 * 104
3. -109 <= nums[i] <= 109

I'm interested in contributing to this repository as part of Hacktoberfest and would love the opportunity to work on this issue. Could you please assign it to me?

**Comment by MayurJirapure11** [comment]
@Kushal997-das plz assign me this issue .

**Comment by g76728443** [comment]
Hi @Kushal997-das,

I know the "Majority Element" problem solution . Could you please assign this issue to me so I can upload my solution?

Thank you!
