### ISSUE TITLE
Add N Queens Problem

### ISSUE THREAD

**Issue by Ayush-Garg1** [Kushal997-das/Hacktoberfest-2021#178]
Problem Statement: **N Queens**

**Description**: 
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.
Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.
Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

**Input**:
An integer `n`

**Output**:
A list of all possible placements.

**Example**:
Input: n = 4
Output: [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]
Explanation: There exist two distinct solutions to the 4-queens puzzle as shown above

**Constraints**:
1 <= n <= 9

**PLEASE ASSIGN THIS ISSUE TO ME AS PART OF HACKTOBERFEST 2024.**
**THANK YOU**

**Comment by Ghanshyam-07** [comment]
Hi @Kushal997-das,

I know the solution of "Add N Queens Problem" . Could you please assign this issue to me so I can upload my solution?

Thank you!

**Comment by swarupsahu08** [comment]
Hey @Kushal997-das ,
I know the solution to this problem .Could you please assign this issue to me so I can update the repository with my code
