### ISSUE TITLE
Add Recursion basic problems

### ISSUE THREAD

**Issue by Upendra48** [Kushal997-das/Hacktoberfest-2021#184]
I would like to add few basic recursion problems like:
1. Sum of the element of an array using recursion
2. Linear search using recursion
3. Find the peak in the mountain array using recursion
4. Find the pivot in a rotated sorted array using recursion 
and so on.

(Please hacktoberfest label)

**Comment by helloshalini** [comment]
hi @Kushal997-das ,
I would like to add few basic recursion problems like:

1. Find factorial using recursion
2. Linear search using recursion
3. Find the peak in the mountain array using recursion

**Comment by Upendra48** [comment]
Hi, @helloshalini I am currently working in this issue, and i have finished the task and soon will be creating a **pull request**, 
so I request to find some other issue or create your own, to start contributing rather than this one and about recursion.

**Comment by avanish2411** [comment]
I want to some good questions and solution in this. 
Assign this to me.
