### ISSUE TITLE
Adding a Program for Binary Search in Sorted Array

### ISSUE THREAD

**Issue by MPrathamjain** [Kushal997-das/Hacktoberfest-2021#206]
Binary Search is a technique to search an element in sorted array in log (N) N= number of elements.

**Comment by Ghanshyam-07** [comment]
Hi @Kushal997-das,

I know  how to Adding a Program for Binary Search in Sorted Array efficiently. Could you please assign this issue to me so I can upload my solution?

Thank you!

**Comment by pushkardubey997** [comment]
Hi @Kushal997-das  , I can provide the optimised solution for this above problem. Kindly assign me this issue.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
