### ISSUE TITLE
Volume down: volume control with notifications (dunst)

### ISSUE THREAD

**Issue by sukalaper** [Kushal997-das/Hacktoberfest-2021#210]
In a [window manager](https://wiki.archlinux.org/title/Window_manager), it may be necessary to reduce the volume or vice versa. It utilizes [Dunst](https://wiki.archlinux.org/title/Dunst) as notification and also Bash as programming language.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
