### ISSUE TITLE
Add Longest Consecutive Sequence

### ISSUE THREAD

**Issue by govindmohan0** [Kushal997-das/Hacktoberfest-2021#214]
Description: Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.

The algorithm must run in O(n) time.

Input:
An array of integers nums.

Output:
An integer representing the length of the longest consecutive sequence.

Example:

Example 1:
Input: nums = [100, 4, 200, 1, 3, 2]
Output: 4
Explanation: The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.

Example 2:
Input: nums = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]
Output: 9

Constraints:
0 <= nums.length <= 10^5
-10^9 <= nums[i] <= 10^9

We can solve using a unordered_set approach keeping track of starting position of a particular sequence and try to find maximum length

**Comment by avanish2411** [comment]
Assign this to me

**Comment by pushkardubey997** [comment]
Hi @Kushal997-das  I can give the optimised solution for this above problem. Kindly assign me this issue.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
