### ISSUE TITLE
Set Matrix Zeroes

### ISSUE THREAD

**Issue by ig-nikhil** [Kushal997-das/Hacktoberfest-2021#274]
Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's.

You must do it in place

![image](https://github.com/user-attachments/assets/af246856-fbea-49f7-8f69-1095d6ea0f4f)

Input: matrix = [[1,1,1],[1,0,1],[1,1,1]]
Output: [[1,0,1],[0,0,0],[1,0,1]]
Constraints:

m == matrix.length
n == matrix[0].length
1 <= m, n <= 200
-231 <= matrix[i][j] <= 231 - 1

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
