### ISSUE TITLE
Create a calculator in TS

### ISSUE THREAD

**Issue by AvidCoder101** [Kushal997-das/Hacktoberfest-2021#278]
Question: create a calculator in typescript that includes the following calculations:
- Adding
- Subtracting
- Multiplying
- Dividing
- Squaring
- Cubing
- Find square root
- Find cube root

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
