### ISSUE TITLE
Text Alignment Solution

### ISSUE THREAD

**Issue by tarunbalajiks** [Kushal997-das/Hacktoberfest-2021#282]
Text Alignment HackerRank problem Solution in Python

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!

**Comment by tarunbalajiks** [comment]
Hey Kushal!
Thank you for the Opportunity to Contribute to SkillShow.
I have made a PR and Raised an Issue regarding the "Text Alignment" Problem
on Hackerrank. Would be grateful if you can look into it and assign the
issue to me / merge the PR.

Thanking you,
Tarun Balaji K S
