### ISSUE TITLE
Contributions to SkillShow Repository

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Hacktoberfest-2021#285]
### Hello Everyone!

**SkillShow** is a new repository where we can contribute to advance our skills. Although this repo has been excluded from Hacktoberfest 2024, we still welcome contributions!

Guidelines:

Please follow the existing guidelines in the repository.
Do not create any additional rules.
Link to the project: [SkillShow](https://github.com/Kushal997-das/SkillShow)

Looking forward to everyone’s contributions!

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
