### ISSUE TITLE
File Search Automation Project

### ISSUE THREAD

**Issue by debojit11** [Kushal997-das/Hacktoberfest-2021#290]
A script that searches a folder you specify (as well as its subfolders, up to two levels deep) and compiles a list of all  file types contained in there. Another list should include the complete path of each file.
Please assign this to me

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
