### ISSUE TITLE
N-Queens (Leetcode question 51)

### ISSUE THREAD

**Issue by DhairyaKaithwar** [Kushal997-das/Hacktoberfest-2021#300]
### I want to add this question

![image](https://github.com/user-attachments/assets/e41496fa-990d-4aca-ac7e-6238887eb9ec)
### Example testcase
![image](https://github.com/user-attachments/assets/676c2103-925d-4aeb-8845-98096322c3cb)

**Comment by yadavmangesh07** [comment]
@DhairyaKaithwar @Kushal997-das , can you please assign this issue to me?

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
