### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by faizulhaq7** [Kushal997-das/Hacktoberfest-2021#303]
Write a program to find the length of the longest substring without repeating characters from a given string. The solution should be optimized to run in O(n) time complexity, using a sliding window and hash map to track character frequencies.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
