### ISSUE TITLE
Find Maximum

### ISSUE THREAD

**Issue by dev-ayomide** [Kushal997-das/Hacktoberfest-2021#304]
Write a function `find_maximum(arr)` that takes a list of integers `arr` as input and returns the maximum value from the list.

**Comment by avanish2411** [comment]
Assign this to me.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
