### ISSUE TITLE
Add "Health Ease System" – C# Windows Desktop Application

### ISSUE THREAD

**Issue by syedmaazsaeed** [Kushal997-das/Hacktoberfest-2021#318]
Hi @Kushal997-das 

I would like to contribute my C# semester project to your repository as part of Hacktoberfest 2024.

 The project is called Health Ease System, a Windows desktop application developed using C# Windows Forms for the frontend and SQL Server for the backend.

Project Details:

Project Name: Health Ease System

Frontend: C# Windows Forms

Backend: SQL Server

Project Images :

![Seller](https://github.com/user-attachments/assets/f4b92ba8-146f-4d36-8a8e-f7a5bb837bbc)
![Medicine-Cell](https://github.com/user-attachments/assets/644d5e93-1a32-47b5-aace-6d1e3e07b421)
![Manufacturer-Details](https://github.com/user-attachments/assets/785b1361-1e7f-47a6-a5e4-e24dc92b4201)
![Dashboard-Panel](https://github.com/user-attachments/assets/14e0a977-6842-41db-ab0e-f0ae3cb36ecd)
![Customer-Section](https://github.com/user-attachments/assets/43c8d404-ab0e-4541-bc45-6998e790f0cf)

I would like to fork the repository and contribute the project code, including assets and all related files.
Please assign this issue to me and grant the maintainer permission for the pull request process.

 could you confirm if this repository is participating in Hacktoberfest 2024?

Thank you for your consideration!

**Comment by neyhere07** [comment]
Hello @syedmaazsaeed! This repository has been excluded from Hacktoberfest 2024, a new repository named [Skill Show](https://github.com/Kushal997-das/SkillShow) has been created where you can contribute. Read all the details in the contributing guidelines carefully.

**Comment by syedmaazsaeed** [comment]
Okay

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
