### ISSUE TITLE
UPDATION IN README.md FILE REQUIRED

### ISSUE THREAD

**Issue by soham0028** [Kushal997-das/Hacktoberfest-2021#336]
hello @Kushal997-das 
the current readme file does not contain following:
1. Table of contents 
2. forkers and stargazers section 
3. back to top button 
4. featured in section 

Kindly Assign me the issue with Hacktoberfest labels for my work to be counted .

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
