### ISSUE TITLE
Add Kruskal's Algorithm Implementation in C++

### ISSUE THREAD

**Issue by Keyur2311** [Kushal997-das/Hacktoberfest-2021#338]
Hey @Kushal997-das , I propose adding an implementation of **Kruskal's Algorithm** in C++ to find the minimum spanning tree of a connected, undirected graph. The output will contain the edges and the cost of minimum spanning tree built with Krushal's algorithm.

**Input:**
1
5 7
0 1 10
0 2 6
0 3 5
1 3 15
2 3 4
1 2 8
2 4 3

**Output:**
Edegs in MST are :-
2 -> 4
0 -> 3
0 -> 1
Total cost of MST is : 18

can you please assign me this issue?
Thank You.

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
