### ISSUE TITLE
pascal's triangle

### ISSUE THREAD

**Issue by taneeshamadhu18** [Kushal997-das/Hacktoberfest-2021#347]
Given an integer numRows, return the first numRows of Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it.

**Comment by Samruddhi345A** [comment]
Hi! I want to contribute to this. Please assign me this issue.

**Comment by taneeshamadhu18** [comment]
@Kushal997-das hey could you add hactoberfest label to this repo? as it is excluded

**Comment by aryanayush012** [comment]
please assign this issue to me

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
