### ISSUE TITLE
Implement Two Sum Algorithm

### ISSUE THREAD

**Issue by rugved0102** [Kushal997-das/Hacktoberfest-2021#354]
Implement a function to solve the "Two Sum" problem. Given an array of integers (nums) and an integer (target), the goal is to return the indices of two numbers from the array such that their sum equals the target. 

You must assume that:

Each input will have exactly one solution.
The same element cannot be used twice.
The result can be returned in any order.
Example Input/Output:
Example 1:

Input: nums = [2, 7, 11, 15], target = 9
Output: [0, 1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

**Comment by aryanayush012** [comment]
I want to work on it
please assign me this

**Comment by rugved0102** [comment]
@Kushal997-das  Can you please assign me the issue ?

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
