### ISSUE TITLE
Program for Sum of Digits Until a Single Digit is Obtained

### ISSUE THREAD

**Issue by Ansh-Vikalp** [Kushal997-das/Hacktoberfest-2021#355]
### **Problem:**
Write a Java program to calculate the sum of the digits of a given number repeatedly until a single digit is obtained.

### **Input:**
A single integer n (positive).
### **Output:**
A single digit representing the sum of the digits, repeatedly calculated until the result is a single digit.

### **Example:**
Input: 9875
Output: 2 (Explanation: 9+8+7+5 = 29 → 2+9 = 11 → 1+1 = 2)

Input: 1245
Output: 3 (Explanation: 5+4+2+1 = 12 → 2+1 = 3)

Input : 7
Output: 7 (Explanation: 7 is single digit by itself)

**Comment by Ansh-Vikalp** [comment]
Hi, @Kushal997-das please assign this issue to me.

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
