### ISSUE TITLE
This Hacktoberfest-2024 Repository is Excluded.

### ISSUE THREAD

**Issue by Ansh-Vikalp** [Kushal997-das/Hacktoberfest-2021#358]
Hey!, @Kushal997-das I made two contribution to your repository "Hacktoberfest-2024", but when i have checked my contribution status on official website of hacktoberfest- https://hacktoberfest.com/profile/ it shows that your **repos has been excluded** as it does not follows values of event. All the contribution made will not be counted to this repo.
![Tru](https://github.com/user-attachments/assets/8adfa1c5-07c0-478c-b2ca-595a3a768379)

![UYt](https://github.com/user-attachments/assets/385631e6-b13b-4f26-8909-a95f5aece614)

**Comment by Kushal997-das** [comment]
> Hey!, @Kushal997-das I made two contribution to your repository "Hacktoberfest-2024", but when i have checked my contribution status on official website of hacktoberfest- https://hacktoberfest.com/profile/ it shows that your **repos has been excluded** as it does not follows values of event then why you allowed all of us contribute and even merging them. All the contribution made will not be counted to this repo. ![Tru](https://private-user-images.githubusercontent.com/92860846/375951875-8adfa1c5-07c0-478c-b2ca-595a3a768379.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzMxMTcsIm5iZiI6MTcyODczMjgxNywicGF0aCI6Ii85Mjg2MDg0Ni8zNzU5NTE4NzUtOGFkZmExYzUtMDdjMC00NzhjLWIyY2EtNTk1YTNhNzY4Mzc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExMzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1M2I3YjhmZTU2NTcxMWVkMzQwNDJkMzcwNDhlZjliOTYwNzA5N2E5OTI5YTNhYTcyNDllODIzMjAyZjJhOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FNgXMhUgdYg9YjNiMFQynjWQsycY1wJRyJdM3vTA4lU)
> 
> ![UYt](https://private-user-images.githubusercontent.com/92860846/375952166-385631e6-b13b-4f26-8909-a95f5aece614.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzMxMTcsIm5iZiI6MTcyODczMjgxNywicGF0aCI6Ii85Mjg2MDg0Ni8zNzU5NTIxNjYtMzg1NjMxZTYtYjEzYi00ZjI2LTg5MDktYTk1ZjVhZWNlNjE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExMzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmRhYzExNTk3ZTdmZDMyZmFmNGVjZGMwMWQ1ZGFhMjUyZGM5M2NiZGIyODExZTY5YmQ3NGQzNTQ3ZWVhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UXUDI9OcH9Y6vXzyM-V5t4XhDra4bsF7-a-WCxyTiVE)


Hello first of tell me where i did merge your any project? Secondly can’t you see the pin issue even we manually comment on every issue about this can’t you see that?  Now I can’t go to your home and tell you that this repo is being excluded right?

**Comment by Ansh-Vikalp** [comment]
Oh, @Kushal997-das I apologize for that. The pinned issue not being displayed in my previous response perhaps due to a connection issue. Is Skill show a valid repo that i can contribute to?
