### ISSUE TITLE
Pong Game

### ISSUE THREAD

**Issue by aryappoovaiah** [Kushal997-das/Hacktoberfest-2021#359]
Problem:
Create a ping pong game using Python.

Solution:
Created ping pong game for two players by importing the Python Module Turtle.

**Comment by Ghanshyam-07** [comment]
I can solve this issue. @Kushal997-das, please assign it to me

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!

**Comment by Ghanshyam-07** [comment]
I want to contribute in this , please assign it to me
