### ISSUE TITLE
Floor in a sorted array

### ISSUE THREAD

**Issue by Aishwarya-S-Sharma** [Kushal997-das/Hacktoberfest-2021#372]
**Floor in a Sorted Array**

**Problem:**
Given a sorted array arr[] of size n without duplicates, and given a value x. Floor of x is defined as the largest element k in arr[] such that k is smaller than or equal to x. Find the index of k(0-based indexing).

**Examples**
**Input:** n = 7, x = 0 arr[] = {1,2,8,10,11,12,19}
**Output:** -1
Explanation: No element less than 0 is found. So output is "-1".

**Input:** n = 7, x = 5 arr[] = {1,2,8,10,11,12,19}
**Output:** 1
Explanation: Largest Number less than 5 is 2 (i.e k = 2), whose index is 1(0-based indexing).

**Your Task:**
The task is to complete the function findFloor() which returns an integer denoting the index value of K or return -1 if there isn't any such number.

**Comment by Aishwarya-S-Sharma** [comment]
Hii @Kushal997-das please assign this to me

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
