### ISSUE TITLE
Search Insert Position 

### ISSUE THREAD

**Issue by Aishwarya-S-Sharma** [Kushal997-das/Hacktoberfest-2021#374]
**Problem**
Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

**Example 1:**
**Input:** nums = [1,3,5,6], target = 5
**Output:** 2

**Example 2:**
**Input:** nums = [1,3,5,6], target = 2
**Output:** 1

**Example 3:**
**Input:** nums = [1,3,5,6], target = 7
**Output:** 4

**Comment by Aishwarya-S-Sharma** [comment]
Hii @Kushal997-das please assign this issue to me

**Comment by aryanayush012** [comment]
please assign this issue to me

**Comment by shalupatidar22** [comment]
Hii @Kushal997-das I want to solve this issue please assign this issue to me

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
