### ISSUE TITLE
 Length of the Longest Subsequence That Sums to Target

### ISSUE THREAD

**Issue by bindaldhara** [Kushal997-das/Hacktoberfest-2021#383]
You are given a 0-indexed array of integers nums, and an integer target.

Return the length of the longest subsequence of nums that sums up to target. If no such subsequence exists, return -1.

A subsequence is an array that can be derived from another array by deleting some or no elements without changing the order of the remaining elements.

**Comment by aryanayush012** [comment]
i want to contribute to this
please assign me this

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
