### ISSUE TITLE
Program to merge two linked list

### ISSUE THREAD

**Issue by mahendra1290** [Kushal997-das/Hacktoberfest-2021#387]
Given two singly linked lists, merge them into a single sorted linked list. The nodes of the merged list should be arranged in ascending order, and the function should return the head of the new merged list. Both input lists are already sorted in ascending order.

Input: Two linked lists (sorted).
Output: A single merged sorted linked list.

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!
