### ISSUE TITLE
Two Sum problem - Input array is sorted

### ISSUE THREAD

**Issue by Mayukh0108** [Kushal997-das/Hacktoberfest-2021#416]
Given a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number. Let these two numbers be numbers[index1] and numbers[index2] where 1 <= index1 < index2 <= numbers.length.

Return the indices of the two numbers, index1 and index2, added by one as an integer array [index1, index2] of length 2.

The tests are generated such that there is exactly one solution. You may not use the same element twice.

Your solution must use only constant extra space.

**Comment by Mayukh0108** [comment]
Hi @Kushal997-das,
Please assign this issue to me, under hacktoberfest24.

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!

**Comment by Mayukh0108** [comment]
> Hi there! I am the Mentor of this project. Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!
> 
> Guidelines:
> 
> * Please adhere to the existing guidelines.
> * No additional rules, thanks!
> * Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
> 
> Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.
> 
> Looking forward to your contributions!

Thanks a lot
