### ISSUE TITLE
Rock, Paper, Scissors game

### ISSUE THREAD

**Issue by iamasraful** [Kushal997-das/Hacktoberfest-2021#420]
A simple and fun game called "Rock, Paper, Scissors". This is a two-player game where each player selects one of three options: Rock, Paper, or Scissors. The rules are simple:

- Rock crushes Scissors.

- Scissors cuts Paper.

- Paper covers Rock.

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!

**Comment by iamasraful** [comment]
Thank you so much <3
